packages:
  - 'packages/*'
  - 'examples/*'
  - './website'
  - './'

allowBuilds:
  esbuild: true
  vue-demi: true

overrides:
  gql.tada: workspace:*
  '@gql.tada/internal': workspace:*
  astro-expressive-code: ^0.31.0
  typescript: ^5.5.2
  '@0no-co/graphqlsp': ^1.12.9
