/* This file is generated by `src/server/__tests__/spec.test.ts` from `kitchenSinkSDL` */
export type kitchenSinkIntrospection = {
  name: never;
  query: 'RootQuery';
  mutation: 'RootMutation';
  subscription: 'RootSubscription';
  types: {
    DateTime: unknown;
    JSON: unknown;
    Node: {
      kind: 'INTERFACE';
      name: 'Node';
      fields: {
        id: {
          name: 'id';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null };
          };
        };
      };
      possibleTypes: 'User' | 'Post';
    };
    ID: unknown;
    Entity: {
      kind: 'INTERFACE';
      name: 'Entity';
      fields: {
        id: {
          name: 'id';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null };
          };
        };
        createdAt: {
          name: 'createdAt';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null };
          };
        };
      };
      possibleTypes: 'User' | 'Post';
    };
    Role: { name: 'Role'; enumValues: 'ADMIN' | 'MEMBER' | 'GUEST' };
    SortDirection: { name: 'SortDirection'; enumValues: 'ASC' | 'DESC' };
    UserOrderField: { name: 'UserOrderField'; enumValues: 'NAME' | 'CREATED_AT' };
    UserOrder: {
      kind: 'INPUT_OBJECT';
      name: 'UserOrder';
      isOneOf: false;
      inputFields: {
        field: {
          name: 'field';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'ENUM'; name: 'UserOrderField'; ofType: null };
          };
          defaultValue: null;
        };
        direction: {
          name: 'direction';
          type: { kind: 'ENUM'; name: 'SortDirection'; ofType: null };
          defaultValue: 'ASC';
        };
      };
    };
    UserFilter: {
      kind: 'INPUT_OBJECT';
      name: 'UserFilter';
      isOneOf: false;
      inputFields: {
        name: {
          name: 'name';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
          defaultValue: null;
        };
        role: {
          name: 'role';
          type: { kind: 'ENUM'; name: 'Role'; ofType: null };
          defaultValue: null;
        };
        and: {
          name: 'and';
          type: {
            kind: 'LIST';
            name: never;
            ofType: {
              kind: 'NON_NULL';
              name: never;
              ofType: { kind: 'INPUT_OBJECT'; name: 'UserFilter'; ofType: null };
            };
          };
          defaultValue: null;
        };
        or: {
          name: 'or';
          type: {
            kind: 'LIST';
            name: never;
            ofType: {
              kind: 'NON_NULL';
              name: never;
              ofType: { kind: 'INPUT_OBJECT'; name: 'UserFilter'; ofType: null };
            };
          };
          defaultValue: null;
        };
        legacyName: {
          name: 'legacyName';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
          defaultValue: null;
        };
      };
    };
    String: unknown;
    UserBy: {
      kind: 'INPUT_OBJECT';
      name: 'UserBy';
      isOneOf: true;
      inputFields: {
        id: { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null }; defaultValue: null };
        name: {
          name: 'name';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
          defaultValue: null;
        };
      };
    };
    CreatePostInput: {
      kind: 'INPUT_OBJECT';
      name: 'CreatePostInput';
      isOneOf: false;
      inputFields: {
        title: {
          name: 'title';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'String'; ofType: null };
          };
          defaultValue: null;
        };
        authorId: {
          name: 'authorId';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null };
          };
          defaultValue: null;
        };
        tags: {
          name: 'tags';
          type: {
            kind: 'LIST';
            name: never;
            ofType: {
              kind: 'NON_NULL';
              name: never;
              ofType: { kind: 'SCALAR'; name: 'String'; ofType: null };
            };
          };
          defaultValue: '[]';
        };
      };
    };
    User: {
      kind: 'OBJECT';
      name: 'User';
      fields: {
        id: {
          name: 'id';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null };
          };
        };
        createdAt: {
          name: 'createdAt';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null };
          };
        };
        name: {
          name: 'name';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'String'; ofType: null };
          };
        };
        nickname: { name: 'nickname'; type: { kind: 'SCALAR'; name: 'String'; ofType: null } };
        role: {
          name: 'role';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'ENUM'; name: 'Role'; ofType: null };
          };
        };
        friends: {
          name: 'friends';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: {
              kind: 'LIST';
              name: never;
              ofType: {
                kind: 'NON_NULL';
                name: never;
                ofType: { kind: 'OBJECT'; name: 'User'; ofType: null };
              };
            };
          };
        };
        matrix: {
          name: 'matrix';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: {
              kind: 'LIST';
              name: never;
              ofType: {
                kind: 'LIST';
                name: never;
                ofType: {
                  kind: 'NON_NULL';
                  name: never;
                  ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null };
                };
              };
            };
          };
        };
        posts: {
          name: 'posts';
          type: {
            kind: 'LIST';
            name: never;
            ofType: {
              kind: 'NON_NULL';
              name: never;
              ofType: { kind: 'OBJECT'; name: 'Post'; ofType: null };
            };
          };
        };
        meta: { name: 'meta'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null } };
      };
    };
    Int: unknown;
    Boolean: unknown;
    Post: {
      kind: 'OBJECT';
      name: 'Post';
      fields: {
        id: {
          name: 'id';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null };
          };
        };
        createdAt: {
          name: 'createdAt';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null };
          };
        };
        title: {
          name: 'title';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'String'; ofType: null };
          };
        };
        tags: {
          name: 'tags';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: {
              kind: 'LIST';
              name: never;
              ofType: {
                kind: 'NON_NULL';
                name: never;
                ofType: { kind: 'SCALAR'; name: 'String'; ofType: null };
              };
            };
          };
        };
        author: {
          name: 'author';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'OBJECT'; name: 'User'; ofType: null };
          };
        };
      };
    };
    SearchResult: {
      kind: 'UNION';
      name: 'SearchResult';
      fields: {};
      possibleTypes: 'User' | 'Post';
    };
    RootQuery: {
      kind: 'OBJECT';
      name: 'RootQuery';
      fields: {
        node: { name: 'node'; type: { kind: 'INTERFACE'; name: 'Node'; ofType: null } };
        user: { name: 'user'; type: { kind: 'OBJECT'; name: 'User'; ofType: null } };
        users: {
          name: 'users';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: {
              kind: 'LIST';
              name: never;
              ofType: {
                kind: 'NON_NULL';
                name: never;
                ofType: { kind: 'OBJECT'; name: 'User'; ofType: null };
              };
            };
          };
        };
        search: {
          name: 'search';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: {
              kind: 'LIST';
              name: never;
              ofType: {
                kind: 'NON_NULL';
                name: never;
                ofType: { kind: 'UNION'; name: 'SearchResult'; ofType: null };
              };
            };
          };
        };
        entities: {
          name: 'entities';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: {
              kind: 'LIST';
              name: never;
              ofType: {
                kind: 'NON_NULL';
                name: never;
                ofType: { kind: 'INTERFACE'; name: 'Entity'; ofType: null };
              };
            };
          };
        };
        now: {
          name: 'now';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null };
          };
        };
        echo: { name: 'echo'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null } };
      };
    };
    RootMutation: {
      kind: 'OBJECT';
      name: 'RootMutation';
      fields: {
        createPost: {
          name: 'createPost';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'OBJECT'; name: 'Post'; ofType: null };
          };
        };
        deletePost: {
          name: 'deletePost';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null };
          };
        };
      };
    };
    RootSubscription: {
      kind: 'OBJECT';
      name: 'RootSubscription';
      fields: {
        postCreated: {
          name: 'postCreated';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'OBJECT'; name: 'Post'; ofType: null };
          };
        };
      };
    };
    __Schema: {
      kind: 'OBJECT';
      name: '__Schema';
      fields: {
        description: {
          name: 'description';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
        };
        types: {
          name: 'types';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: {
              kind: 'LIST';
              name: never;
              ofType: {
                kind: 'NON_NULL';
                name: never;
                ofType: { kind: 'OBJECT'; name: '__Type'; ofType: null };
              };
            };
          };
        };
        queryType: {
          name: 'queryType';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'OBJECT'; name: '__Type'; ofType: null };
          };
        };
        mutationType: {
          name: 'mutationType';
          type: { kind: 'OBJECT'; name: '__Type'; ofType: null };
        };
        subscriptionType: {
          name: 'subscriptionType';
          type: { kind: 'OBJECT'; name: '__Type'; ofType: null };
        };
        directives: {
          name: 'directives';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: {
              kind: 'LIST';
              name: never;
              ofType: {
                kind: 'NON_NULL';
                name: never;
                ofType: { kind: 'OBJECT'; name: '__Directive'; ofType: null };
              };
            };
          };
        };
      };
    };
    __Type: {
      kind: 'OBJECT';
      name: '__Type';
      fields: {
        kind: {
          name: 'kind';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'ENUM'; name: '__TypeKind'; ofType: null };
          };
        };
        name: { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null } };
        description: {
          name: 'description';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
        };
        specifiedByURL: {
          name: 'specifiedByURL';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
        };
        fields: {
          name: 'fields';
          type: {
            kind: 'LIST';
            name: never;
            ofType: {
              kind: 'NON_NULL';
              name: never;
              ofType: { kind: 'OBJECT'; name: '__Field'; ofType: null };
            };
          };
        };
        interfaces: {
          name: 'interfaces';
          type: {
            kind: 'LIST';
            name: never;
            ofType: {
              kind: 'NON_NULL';
              name: never;
              ofType: { kind: 'OBJECT'; name: '__Type'; ofType: null };
            };
          };
        };
        possibleTypes: {
          name: 'possibleTypes';
          type: {
            kind: 'LIST';
            name: never;
            ofType: {
              kind: 'NON_NULL';
              name: never;
              ofType: { kind: 'OBJECT'; name: '__Type'; ofType: null };
            };
          };
        };
        enumValues: {
          name: 'enumValues';
          type: {
            kind: 'LIST';
            name: never;
            ofType: {
              kind: 'NON_NULL';
              name: never;
              ofType: { kind: 'OBJECT'; name: '__EnumValue'; ofType: null };
            };
          };
        };
        inputFields: {
          name: 'inputFields';
          type: {
            kind: 'LIST';
            name: never;
            ofType: {
              kind: 'NON_NULL';
              name: never;
              ofType: { kind: 'OBJECT'; name: '__InputValue'; ofType: null };
            };
          };
        };
        ofType: { name: 'ofType'; type: { kind: 'OBJECT'; name: '__Type'; ofType: null } };
        isOneOf: { name: 'isOneOf'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null } };
      };
    };
    __TypeKind: {
      name: '__TypeKind';
      enumValues:
        | 'SCALAR'
        | 'OBJECT'
        | 'INTERFACE'
        | 'UNION'
        | 'ENUM'
        | 'INPUT_OBJECT'
        | 'LIST'
        | 'NON_NULL';
    };
    __Field: {
      kind: 'OBJECT';
      name: '__Field';
      fields: {
        name: {
          name: 'name';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'String'; ofType: null };
          };
        };
        description: {
          name: 'description';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
        };
        args: {
          name: 'args';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: {
              kind: 'LIST';
              name: never;
              ofType: {
                kind: 'NON_NULL';
                name: never;
                ofType: { kind: 'OBJECT'; name: '__InputValue'; ofType: null };
              };
            };
          };
        };
        type: {
          name: 'type';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'OBJECT'; name: '__Type'; ofType: null };
          };
        };
        isDeprecated: {
          name: 'isDeprecated';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null };
          };
        };
        deprecationReason: {
          name: 'deprecationReason';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
        };
      };
    };
    __InputValue: {
      kind: 'OBJECT';
      name: '__InputValue';
      fields: {
        name: {
          name: 'name';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'String'; ofType: null };
          };
        };
        description: {
          name: 'description';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
        };
        type: {
          name: 'type';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'OBJECT'; name: '__Type'; ofType: null };
          };
        };
        defaultValue: {
          name: 'defaultValue';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
        };
        isDeprecated: {
          name: 'isDeprecated';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null };
          };
        };
        deprecationReason: {
          name: 'deprecationReason';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
        };
      };
    };
    __EnumValue: {
      kind: 'OBJECT';
      name: '__EnumValue';
      fields: {
        name: {
          name: 'name';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'String'; ofType: null };
          };
        };
        description: {
          name: 'description';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
        };
        isDeprecated: {
          name: 'isDeprecated';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null };
          };
        };
        deprecationReason: {
          name: 'deprecationReason';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
        };
      };
    };
    __Directive: {
      kind: 'OBJECT';
      name: '__Directive';
      fields: {
        name: {
          name: 'name';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'String'; ofType: null };
          };
        };
        description: {
          name: 'description';
          type: { kind: 'SCALAR'; name: 'String'; ofType: null };
        };
        isRepeatable: {
          name: 'isRepeatable';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null };
          };
        };
        locations: {
          name: 'locations';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: {
              kind: 'LIST';
              name: never;
              ofType: {
                kind: 'NON_NULL';
                name: never;
                ofType: { kind: 'ENUM'; name: '__DirectiveLocation'; ofType: null };
              };
            };
          };
        };
        args: {
          name: 'args';
          type: {
            kind: 'NON_NULL';
            name: never;
            ofType: {
              kind: 'LIST';
              name: never;
              ofType: {
                kind: 'NON_NULL';
                name: never;
                ofType: { kind: 'OBJECT'; name: '__InputValue'; ofType: null };
              };
            };
          };
        };
      };
    };
    __DirectiveLocation: {
      name: '__DirectiveLocation';
      enumValues:
        | 'QUERY'
        | 'MUTATION'
        | 'SUBSCRIPTION'
        | 'FIELD'
        | 'FRAGMENT_DEFINITION'
        | 'FRAGMENT_SPREAD'
        | 'INLINE_FRAGMENT'
        | 'VARIABLE_DEFINITION'
        | 'SCHEMA'
        | 'SCALAR'
        | 'OBJECT'
        | 'FIELD_DEFINITION'
        | 'ARGUMENT_DEFINITION'
        | 'INTERFACE'
        | 'UNION'
        | 'ENUM'
        | 'ENUM_VALUE'
        | 'INPUT_OBJECT'
        | 'INPUT_FIELD_DEFINITION';
    };
  };
};
