import { describe, it, expect } from 'vitest';
import type { IntrospectionQuery } from 'graphql';
import {
  buildSchema,
  printSchema,
  lexicographicSortSchema,
  introspectionFromSchema,
  validateSchema,
  specifiedDirectives,
} from 'graphql';

import * as prettier from 'prettier';
import { preprocessIntrospection } from '@gql.tada/internal';
import { schema, kitchenSinkSDL } from './fixtures/kitchenSink';

const introspectionOptions = {
  descriptions: true,
  specifiedByUrl: true,
  directiveIsRepeatable: true,
  schemaDescription: true,
  inputValueDeprecation: true,
  oneOf: true,
};

const byName = (a: { name: string }, b: { name: string }) => (a.name < b.name ? -1 : 1);

/** Sorts named types, directives, and possible types, which are ordered by type registration */
const normalize = (introspection: IntrospectionQuery) => ({
  __schema: {
    ...introspection.__schema,
    types: [...introspection.__schema.types]
      .sort(byName)
      .map((type) =>
        'possibleTypes' in type && type.possibleTypes
          ? { ...type, possibleTypes: [...type.possibleTypes].sort(byName) }
          : type
      ),
    directives: [...introspection.__schema.directives].sort(byName),
  },
});

describe('GraphQL specification (September 2025) type system', () => {
  const expected = buildSchema(kitchenSinkSDL);

  it('creates a valid schema', () => {
    expect(validateSchema(schema)).toEqual([]);
  });

  it('matches the same schema defined in SDL', () => {
    expect(printSchema(lexicographicSortSchema(schema))).toBe(
      printSchema(lexicographicSortSchema(expected))
    );
  });

  it('matches the introspection of the same schema defined in SDL', () => {
    const actual = introspectionFromSchema(schema, introspectionOptions);
    expect(normalize(actual)).toEqual(
      normalize(introspectionFromSchema(expected, introspectionOptions))
    );
  });

  it('includes all built-in directives', () => {
    const names = schema.getDirectives().map((directive) => directive.name);
    for (const directive of specifiedDirectives) expect(names).toContain(directive.name);
    expect(names).toEqual(
      expect.arrayContaining(['skip', 'include', 'deprecated', 'specifiedBy', 'oneOf'])
    );
  });

  it('exposes applied type system directives on extensions', () => {
    expect(schema.extensions.directives).toEqual([{ name: 'meta', args: { key: 'schema' } }]);
    expect(schema.getType('DateTime')!.extensions.directives).toEqual([
      { name: 'meta', args: { key: 'format', value: 'iso-8601' } },
    ]);
    expect(schema.getType('SearchResult')!.extensions.directives).toEqual([
      { name: 'meta', args: { key: 'search' } },
    ]);

    const user = schema.getType('User') as any;
    expect(user.extensions.directives).toEqual([
      { name: 'meta', args: { key: 'owner', value: 'accounts' } },
    ]);
    // Repeatable directives may be applied more than once, and keep their order
    expect(user.getFields().posts.extensions.directives).toEqual([
      { name: 'meta', args: { key: 'a' } },
      { name: 'meta', args: { key: 'b' } },
    ]);
    const legacy = user.getFields().friends.args.find((arg: any) => arg.name === 'legacy');
    expect(legacy.extensions.directives).toEqual([{ name: 'meta', args: { key: 'legacy' } }]);

    const role = schema.getType('Role') as any;
    expect(role.getValue('GUEST').extensions.directives).toEqual([
      { name: 'meta', args: { key: 'since', value: '2025' } },
    ]);
  });

  it('matches the gql.tada schema type of the same schema defined in SDL', async () => {
    // The type tests compare the builder's derived schema type against this snapshot
    const introspection = {
      ...introspectionFromSchema(expected, introspectionOptions),
      name: undefined,
    };
    const file = new URL('./fixtures/kitchenSinkIntrospection.ts', import.meta.url).pathname;
    const output = await prettier.format(
      '/* This file is generated by `src/server/__tests__/spec.test.ts` from `kitchenSinkSDL` */\n' +
        `export type kitchenSinkIntrospection = ${preprocessIntrospection(introspection)};\n`,
      { ...(await prettier.resolveConfig(file)), filepath: file }
    );
    await expect(output).toMatchFileSnapshot('./fixtures/kitchenSinkIntrospection.ts');
  });
});
