name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    outputs:
      has_changesets: ${{ steps.changesets.outputs.hasChangesets }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1.8.0
        with:
          version: pnpm changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish
    needs: release
    if: needs.release.outputs.has_changesets == 'false'
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    environment:
      name: npm
      url: https://www.npmjs.com/package/gql.tada
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Update npm
        run: npm install -g npm@11.14.1

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish packages
        id: changesets
        uses: changesets/action@v1.8.0
        with:
          publish: pnpm changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify discord
        id: discord-msg
        if: steps.changesets.outputs.published == 'true'
        uses: ./.github/actions/discord-message
        with:
          publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
