name: CI

on:
  pull_request:
    paths:
      - website/**
  push:
    branches:
      - main
    paths:
      - website/**

jobs:
  site:
    name: Site
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm multi --include-workspace-root run build

      - name: Build Website
        working-directory: website
        run: pnpm run export

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: gql-tada
          workingDirectory: website
          directory: .vitepress/dist
